# Generated by Django 2.2 on 2019-05-01 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('znbpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('summary_html', models.TextField(blank=True, editable=False)),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='img/%Y/%m/', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('image_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('image_credit_html', models.TextField(blank=True, editable=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], default=2)),
                ('enable_comments', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('summary_html', models.TextField(blank=True, editable=False)),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='img/%Y/%m/', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('image_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('image_credit_html', models.TextField(blank=True, editable=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], default=2)),
                ('enable_comments', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryToArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='znbpost.Article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='znbpost.Category')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, through='znbpost.CategoryToArticle', to='znbpost.Category'),
        ),
    ]
